export const categories = [
    {
      id: 9,
      name: "General Knowledge",
      instructions: "Answer the general knowledge questions.",
      available: true,
      maxAttempts: 3,
      timeLimit: 60,
      points: 10,
    },
    {
      id: 10,
      name: "Entertainment: Books",
      instructions: "Answer questions about books and authors.",
      available: true,
      maxAttempts: 3,
      timeLimit: 45,
      points: 15,
    },
    {
      id: 11,
      name: "Entertainment: Film",
      instructions: "Test your knowledge of movies and actors.",
      available: false,
      maxAttempts: 2,
      timeLimit: 90,
      points: 20,
    },
    {
      id: 12,
      name: "Entertainment: Music",
      instructions: "Answer questions about music and musicians.",
      available: true,
      maxAttempts: 3,
      timeLimit: 60,
      points: 15,
    },
    {
      id: 13,
      name: "Entertainment: Musicals & Theatres",
      instructions: "Test your knowledge of musicals and theatres.",
      available: true,
      maxAttempts: 2,
      timeLimit: 45,
      points: 20,
    },
    {
      id: 14,
      name: "Entertainment: Television",
      instructions: "Answer questions about TV shows and series.",
      available: true,
      maxAttempts: 3,
      timeLimit: 60,
      points: 15,
    },
    {
      id: 15,
      name: "Entertainment: Video Games",
      instructions: "Test your knowledge of video games.",
      available: true,
      maxAttempts: 3,
      timeLimit: 45,
      points: 20,
    },
    {
      id: 16,
      name: "Entertainment: Board Games",
      instructions: "Answer questions about board games.",
      available: true,
      maxAttempts: 3,
      timeLimit: 60,
      points: 15,
    },
    {
      id: 17,
      name: "Science & Nature",
      instructions: "Answer questions about science and nature.",
      available: true,
      maxAttempts: 3,
      timeLimit: 45,
      points: 15,
    },
    {
      id: 18,
      name: "Science: Computers",
      instructions: "Test your knowledge of computers and technology.",
      available: true,
      maxAttempts: 2,
      timeLimit: 60,
      points: 20,
    },
    {
      id: 19,
      name: "Science: Mathematics",
      instructions: "Answer questions about mathematics.",
      available: true,
      maxAttempts: 3,
      timeLimit: 45,
      points: 15,
    },
    {
      id: 20,
      name: "Mythology",
      instructions: "Test your knowledge of mythology and folklore.",
      available: true,
      maxAttempts: 2,
      timeLimit: 60,
      points: 20,
    },
    {
      id: 21,
      name: "Sports",
      instructions: "Answer questions about various sports.",
      available: true,
      maxAttempts: 3,
      timeLimit: 45,
      points: 15,
    },
    {
      id: 22,
      name: "Geography",
      instructions: "Test your knowledge of world geography.",
      available: true,
      maxAttempts: 3,
      timeLimit: 60,
      points: 10,
    },
    {
      id: 23,
      name: "History",
      instructions: "Answer questions about historical events.",
      available: true,
      maxAttempts: 3,
      timeLimit: 45,
      points: 15,
    },
    {
      id: 24,
      name: "Politics",
      instructions: "Test your knowledge of politics and governments.",
      available: true,
      maxAttempts: 2,
      timeLimit: 60,
      points: 20,
    },
    {
      id: 25,
      name: "Art",
      instructions: "Answer questions about art and artists.",
      available: true,
      maxAttempts: 3,
      timeLimit: 45,
      points: 15,
    },
    {
      id: 26,
      name: "Celebrities",
      instructions: "Test your knowledge of famous celebrities.",
      available: true,
      maxAttempts: 2,
      timeLimit: 60,
      points: 20,
    },
    {
      id: 27,
      name: "Animals",
      instructions: "Answer questions about various animals.",
      available: true,
      maxAttempts: 3,
      timeLimit: 45,
      points: 15,
    },
    {
      id: 28,
      name: "Vehicles",
      instructions: "Test your knowledge of vehicles and automobiles.",
      available: true,
      maxAttempts: 2,
      timeLimit: 60,
      points: 20,
    },
    {
      id: 29,
      name: "Entertainment: Comics",
      instructions: "Answer questions about comic books and characters.",
      available: true,
      maxAttempts: 3,
      timeLimit: 45,
      points: 15,
    },
    {
      id: 30,
      name: "Science: Gadgets",
      instructions: "Test your knowledge of technological gadgets.",
      available: true,
      maxAttempts: 2,
      timeLimit: 60,
      points: 20,
    },
    {
      id: 31,
      name: "Entertainment: Japanese Anime & Manga",
      instructions: "Answer questions about Japanese anime and manga.",
      available: true,
      maxAttempts: 3,
      timeLimit: 45,
      points: 15,
    },
    {
      id: 32,
      name: "Entertainment: Cartoon & Animations",
      instructions: "Test your knowledge of cartoons and animations.",
      available: true,
      maxAttempts: 2,
      timeLimit: 60,
      points: 20,
    },
  ];
  